위젯 합치기
softwarej1/Nerd_Connection pull request #19
Opened 2023-12-19 16:38 UTC by Obebe-creator

2023-12-21 03:35 UTC, SangWook16074 requested changes

2023-12-21 03:35 UTC, SangWook16074 commented on lib/src/view/profile.dart
> -      body: _body(),
context를 직접 전달하기보다는 Stateful Widget을 사용하는게 어떨까요?

2023-12-24 13:17 UTC, closed without merging

2023-12-24 13:17 UTC, Obebe-creator commented
.

2023-12-24 13:17 UTC, Obebe-creator commented
.